[package]
name = "cddl-lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cbor_event = "2.1.3"
wasm-bindgen = { version = "0.2", features=["serde-serialize"] }
chain-crypto = { path = "./chain-libs/chain-crypto" }
chain-impl-mockchain = { path = "./chain-libs/chain-impl-mockchain" }
bech32 = "0.6"
hex = "0.4.0"
js-sys = "0.3.24"
rand_os = { version = "0.1", features = ["wasm-bindgen"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
